export interface Prompt {
  id: string;
  user: string;
  text: string;
  category: string; // "discovery" | "comparison" | "purchase" | "custom"
  tags: string[];
  isAutoGenerated: boolean;
  lastScannedAt?: string;
  created: string;
}
