import { NextRequest, NextResponse } from "next/server";
import PocketBase from "pocketbase";
import { z, ZodError } from "zod";

const CreatePromptSchema = z.object({
  text: z.string().min(1, "Prompt text is required").max(500, "Prompt text must be under 500 characters"),
  category: z.enum(["discovery", "comparison", "purchase", "custom"]),
  tags: z.array(z.string()).default([]),
  isAutoGenerated: z.boolean().default(false),
});

const UpdatePromptSchema = z.object({
  id: z.string().min(1, "Prompt ID is required"),
  category: z.enum(["discovery", "comparison", "purchase", "custom"]).optional(),
  tags: z.array(z.string()).optional(),
});

function getPocketBase(request: NextRequest) {
  const pbUrl = process.env.NEXT_PUBLIC_POCKETBASE_URL || "http://127.0.0.1:8090";
  const pb = new PocketBase(pbUrl);
  const pbCookie = request.cookies.get("pb_auth");
  if (pbCookie) {
    pb.authStore.loadFromCookie(`pb_auth=${pbCookie.value}`);
  }
  return pb;
}

export async function GET(request: NextRequest) {
  try {
    const pb = getPocketBase(request);
    if (!pb.authStore.isValid || !pb.authStore.record) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const userId = pb.authStore.record.id;
    const { searchParams } = new URL(request.url);
    const category = searchParams.get("category");

    let filter = `user="${userId}"`;
    if (category && category !== "all") {
      filter += ` && category="${category}"`;
    }

    const prompts = await pb.collection("prompts").getFullList({
      filter,
      sort: "-created",
    });

    return NextResponse.json(prompts);
  } catch (error) {
    console.error("[prompts GET]", error);
    return NextResponse.json({ message: "Failed to fetch prompts" }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const validated = CreatePromptSchema.parse(body);

    const pb = getPocketBase(request);
    if (!pb.authStore.isValid || !pb.authStore.record) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const userId = pb.authStore.record.id;

    const prompt = await pb.collection("prompts").create({
      user: userId,
      text: validated.text,
      category: validated.category,
      tags: validated.tags,
      isAutoGenerated: validated.isAutoGenerated,
    });

    return NextResponse.json(prompt, { status: 201 });
  } catch (error) {
    if (error instanceof ZodError) {
      const messages = error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; ");
      return NextResponse.json({ message: `Validation error: ${messages}` }, { status: 400 });
    }

    console.error("[prompts POST]", error);
    return NextResponse.json({ message: "Failed to create prompt" }, { status: 500 });
  }
}

export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json();
    const validated = UpdatePromptSchema.parse(body);

    const pb = getPocketBase(request);
    if (!pb.authStore.isValid || !pb.authStore.record) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const userId = pb.authStore.record.id;

    // Verify ownership before updating
    const existing = await pb.collection("prompts").getOne(validated.id);
    if (existing.user !== userId) {
      return NextResponse.json({ message: "Forbidden" }, { status: 403 });
    }

    const updateData: Record<string, unknown> = {};
    if (validated.category !== undefined) updateData.category = validated.category;
    if (validated.tags !== undefined) updateData.tags = validated.tags;

    const updated = await pb.collection("prompts").update(validated.id, updateData);

    return NextResponse.json(updated);
  } catch (error) {
    if (error instanceof ZodError) {
      const messages = error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; ");
      return NextResponse.json({ message: `Validation error: ${messages}` }, { status: 400 });
    }

    console.error("[prompts PATCH]", error);
    return NextResponse.json({ message: "Failed to update prompt" }, { status: 500 });
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get("id");

    if (!id) {
      return NextResponse.json({ message: "Prompt ID is required" }, { status: 400 });
    }

    const pb = getPocketBase(request);
    if (!pb.authStore.isValid || !pb.authStore.record) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const userId = pb.authStore.record.id;

    // Verify ownership before deleting
    const existing = await pb.collection("prompts").getOne(id);
    if (existing.user !== userId) {
      return NextResponse.json({ message: "Forbidden" }, { status: 403 });
    }

    await pb.collection("prompts").delete(id);

    return NextResponse.json({ message: "Prompt deleted successfully" });
  } catch (error) {
    console.error("[prompts DELETE]", error);
    return NextResponse.json({ message: "Failed to delete prompt" }, { status: 500 });
  }
}
