"use client";

import { useState, useTransition } from "react";
import { Sparkles, Plus, Loader2, AlertCircle } from "lucide-react";
import type { Prompt } from "@/types/prompt";

const CATEGORY_COLORS: Record<string, string> = {
  discovery: "bg-blue-500/10 text-blue-400 border-blue-500/20",
  comparison: "bg-purple-500/10 text-purple-400 border-purple-500/20",
  purchase: "bg-green-500/10 text-green-400 border-green-500/20",
  custom: "bg-zinc-500/10 text-zinc-400 border-zinc-500/20",
};

interface SuggestedPrompt {
  text: string;
  category: string;
}

interface PromptSuggestionsProps {
  brandDomain: string;
  productCategories: string[];
  existingPromptTexts: string[];
  onPromptAdded: (prompt: Prompt) => void;
}

export function PromptSuggestions({
  brandDomain,
  productCategories,
  existingPromptTexts,
  onPromptAdded,
}: PromptSuggestionsProps) {
  const [suggestions, setSuggestions] = useState<SuggestedPrompt[]>([]);
  const [addedIndices, setAddedIndices] = useState<Set<number>>(new Set());
  const [error, setError] = useState("");
  const [isGenerating, startGenerating] = useTransition();
  const [isAdding, startAdding] = useTransition();

  function handleGenerate() {
    setError("");
    setAddedIndices(new Set());
    startGenerating(async () => {
      try {
        const res = await fetch("/api/prompts/suggest", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ brandDomain, productCategories, existingPromptTexts }),
        });

        if (!res.ok) {
          const data = await res.json();
          setError(data.message || "Failed to generate suggestions.");
          return;
        }

        const data = await res.json();
        setSuggestions(data.suggestions ?? []);
      } catch {
        setError("Network error. Please try again.");
      }
    });
  }

  function handleAdd(suggestion: SuggestedPrompt, index: number) {
    startAdding(async () => {
      try {
        const res = await fetch("/api/prompts", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            text: suggestion.text,
            category: suggestion.category,
            tags: [],
            isAutoGenerated: true,
          }),
        });

        if (!res.ok) {
          return;
        }

        const newPrompt = await res.json();
        setAddedIndices((prev) => new Set(prev).add(index));
        onPromptAdded(newPrompt);
      } catch {
        console.error("Failed to add prompt suggestion");
      }
    });
  }

  return (
    <div className="bg-bg-secondary border border-border rounded-lg p-6 space-y-5">
      <div>
        <h2 className="text-lg font-semibold text-text-primary mb-1">AI Suggestions</h2>
        <p className="text-sm text-text-tertiary">
          Let Claude generate search prompts tailored to your brand and product categories.
        </p>
      </div>

      <button
        onClick={handleGenerate}
        disabled={isGenerating}
        className="flex items-center gap-2 w-full justify-center px-4 py-3 bg-accent-primary hover:bg-accent-primary/90 text-white rounded-lg font-medium text-sm transition-colors disabled:opacity-50"
      >
        {isGenerating ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Generating...
          </>
        ) : (
          <>
            <Sparkles className="w-4 h-4" />
            Generate AI Suggestions
          </>
        )}
      </button>

      {error && (
        <div className="flex items-start gap-2 p-3 bg-error/10 border border-error/20 rounded-lg">
          <AlertCircle className="w-4 h-4 text-error flex-shrink-0 mt-0.5" />
          <p className="text-sm text-error">{error}</p>
        </div>
      )}

      {suggestions.length > 0 && (
        <div className="space-y-3">
          <p className="text-sm text-text-tertiary">
            {suggestions.length} suggestions — click &ldquo;+&rdquo; to add to your prompts
          </p>
          <div className="space-y-2 max-h-[480px] overflow-y-auto pr-1">
            {suggestions.map((s, i) => {
              const isAdded = addedIndices.has(i);
              return (
                <div
                  key={i}
                  className={`flex items-start gap-3 p-3 border rounded-lg transition-colors ${
                    isAdded
                      ? "bg-success/5 border-success/20 opacity-60"
                      : "bg-bg-tertiary border-border hover:border-accent-primary/40"
                  }`}
                >
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-text-primary">{s.text}</p>
                    <span
                      className={`inline-block mt-1.5 px-2 py-0.5 rounded border text-xs font-medium capitalize ${
                        CATEGORY_COLORS[s.category] ?? CATEGORY_COLORS.custom
                      }`}
                    >
                      {s.category}
                    </span>
                  </div>
                  <button
                    onClick={() => handleAdd(s, i)}
                    disabled={isAdded || isAdding}
                    title={isAdded ? "Already added" : "Add to prompts"}
                    className={`flex-shrink-0 p-1.5 rounded-lg transition-colors ${
                      isAdded
                        ? "text-success cursor-default"
                        : "text-text-tertiary hover:text-accent-primary hover:bg-accent-primary/10 disabled:opacity-40"
                    }`}
                  >
                    <Plus className="w-4 h-4" />
                  </button>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {!isGenerating && suggestions.length === 0 && !error && (
        <div className="py-6 text-center">
          <Sparkles className="w-8 h-8 text-text-tertiary mx-auto mb-2 opacity-30" />
          <p className="text-sm text-text-tertiary">
            Click the button above to get tailored prompt suggestions.
          </p>
        </div>
      )}
    </div>
  );
}
