import { createServerClient } from "@/lib/pocketbase/server";
import { redirect } from "next/navigation";
import { MessageSquare } from "lucide-react";
import { PromptsPageClient } from "@/components/prompts/PromptsPageClient";
import type { Prompt } from "@/types/prompt";
import type { SkuRecord, UserRecord } from "@/types/pocketbase";

export default async function PromptsPage() {
  const pb = await createServerClient();

  if (!pb.authStore.isValid || !pb.authStore.record) {
    redirect("/login");
  }

  const userId = pb.authStore.record.id;
  const user = pb.authStore.record as UserRecord;

  let prompts: Prompt[] = [];
  let productCategories: string[] = [];

  try {
    const [rawPrompts, skus] = await Promise.all([
      pb.collection("prompts").getFullList({
        filter: `user="${userId}"`,
        sort: "-created",
      }),
      pb.collection("skus").getFullList<SkuRecord>({
        filter: `user="${userId}"`,
      }),
    ]);

    prompts = rawPrompts.map((p) => ({
      id: p.id,
      user: p.user,
      text: p.text,
      category: p.category,
      tags: Array.isArray(p.tags) ? p.tags : [],
      isAutoGenerated: p.isAutoGenerated ?? false,
      lastScannedAt: p.lastScannedAt,
      created: p.created,
    }));

    // Derive unique product categories from SKUs
    const categorySet = new Set<string>();
    for (const sku of skus) {
      if (sku.category) categorySet.add(sku.category);
    }
    productCategories = Array.from(categorySet);
  } catch (err) {
    console.error("[prompts] Failed to fetch data:", err);
  }

  const brandDomain = user.domain || "";

  return (
    <div className="space-y-8">
      <div>
        <div className="flex items-center gap-3 mb-2">
          <MessageSquare className="w-8 h-8 text-accent-primary" />
          <h1 className="text-4xl font-bold text-text-primary">Prompts</h1>
        </div>
        <p className="text-text-tertiary">
          Manage the search queries used to test your brand&apos;s visibility in AI engines.
          Add prompts manually or generate AI suggestions tailored to your product catalog.
        </p>
      </div>

      <div className="flex gap-4 text-sm">
        <div className="bg-bg-secondary border border-border rounded-lg px-4 py-3">
          <span className="text-text-tertiary">Total Prompts</span>
          <p className="text-2xl font-bold text-text-primary mt-0.5">{prompts.length}</p>
        </div>
        <div className="bg-bg-secondary border border-border rounded-lg px-4 py-3">
          <span className="text-text-tertiary">AI Generated</span>
          <p className="text-2xl font-bold text-text-primary mt-0.5">
            {prompts.filter((p) => p.isAutoGenerated).length}
          </p>
        </div>
        <div className="bg-bg-secondary border border-border rounded-lg px-4 py-3">
          <span className="text-text-tertiary">Categories</span>
          <p className="text-2xl font-bold text-text-primary mt-0.5">
            {new Set(prompts.map((p) => p.category)).size}
          </p>
        </div>
      </div>

      <PromptsPageClient
        initialPrompts={prompts}
        brandDomain={brandDomain}
        productCategories={productCategories}
      />
    </div>
  );
}
